name = "ArgCheck"
uuid = "dce04be8-c92d-5529-be00-80e4d2c0e197"
license = "MIT"
version = "2.3.0"

[compat]
julia = "1"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "BenchmarkTools"]
